# Generated by Django 3.1.5 on 2021-02-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_text', models.TextField(verbose_name='Сгенерированный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.AlterField(
            model_name='keytext',
            name='key_word',
            field=models.CharField(max_length=250, verbose_name='Ключевое слово'),
        ),
        migrations.AddField(
            model_name='keytext',
            name='gen_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gentext', verbose_name='Сгенерированный текст'),
        ),
    ]
