# Generated by Django 3.1.5 on 2021-02-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210218_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keytext',
            old_name='key_word',
            new_name='word',
        ),
    ]
