# Generated by Django 3.1.5 on 2021-02-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210210_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_gentext_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keytext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.TextField(max_length=500, verbose_name='Текст для генерации')),
                ('created_keytext_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
