# Generated by Django 3.1.5 on 2021-02-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gentext_keytext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emil',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
