# Generated by Django 3.1.5 on 2021-02-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210212_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='keytext',
            name='gen_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keytext', to='core.gentext'),
        ),
    ]
